version: "3.9"
services:
  dilan:
    image: eukon/classroom
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/examplename
      SPRING.DATASOURCE.USERNAME: exampleuser
      SPRING.DATASOURCE.PASSWORD: examplepassword
      JWT.SECRET: examplesecret
  postgres:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: examplename
    ports:
      - '5432:5432'
volumes:
  db:
    driver: local