CREATE TABLE APPUSER(username VARCHAR(30) PRIMARY KEY NOT NULL, password VARCHAR(30) NOT NULL, name VARCHAR(30) NOT NULL, surname VARCHAR(30) NOT NULL);
CREATE TABLE COURSE(id int PRIMARY KEY NOT NULL, invite_code VARCHAR(6) NOT NULL, name VARCHAR(30) NOT NULL);
CREATE TABLE ASSIGNMENT(id int PRIMARY KEY NOT NULL, title VARCHAR(30), content TEXT NOT NULL, course_id int NOT NULL);
CREATE TABLE ASSIGNMENT_LINKS(assignment_id int NOT NULL, links VARCHAR NOT NULL);
CREATE TABLE APPUSER_COURSE(is_teacher BOOLEAN NOT NULL, course_id int NOT NULL, app_user_username VARCHAR(30) NOT NULL);
CREATE TABLE APPUSER_COURSES(app_user_username VARCHAR(30) NOT NULL, courses_course_id int NOT NULL, course_app_user_username VARCHAR(30) NOT NULL);
CREATE TABLE COURSE_APP_USERS(course_id int NOT NULL, app_users_course_id int NOT NULL, app_users_app_user_username VARCHAR(30) NOT NULL);